version: '3'

services:
  backend:
    image: docker-spring-boot:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: backend-application
    depends_on:
      - db

  frontend:
    image: reactjs-application:1.0.0
    build:
      context: C:\Users\Livmas\WebstormProjects\silo-web-app
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    container_name: frontend-application
    depends_on:
      - backend
    volumes:
      - /app/node_modules
      - ./frontend:/app

  db:
    image: postgres:14.7-alpine
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=livmas
    ports:
      - "15432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: livmas
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db-data:
  pgadmin-data: