INSERT INTO informations(name, frequency) VALUES('Строил подобные бункеры', 0.2);
INSERT INTO informations(name, frequency) VALUES('Лично знаком с президентом', 0.1);
INSERT INTO informations(name, frequency) VALUES('Служил в армии по контракту', 0.3);
INSERT INTO informations(name, frequency) VALUES('Зарабатывал миллион рублей в месяц', 0.3);
INSERT INTO informations(name, frequency) VALUES('Есть прошлое в спорте', 0.5);
INSERT INTO informations(name, frequency) VALUES('Работал в правительстве', 0.2);
INSERT INTO informations(name, frequency) VALUES('Сидел в тюрьме', 0.4);
INSERT INTO informations(name, frequency) VALUES('Сидел за убийство', 0.2);
INSERT INTO informations(name, frequency) VALUES('Любит животных', 0.7);
INSERT INTO informations(name, frequency) VALUES('Было 10 кошек', 0.4);
INSERT INTO informations(name, frequency) VALUES('Имеет видеоблог', 0.3);
INSERT INTO informations(name, frequency) VALUES('Снимался в кино', 0.2);
INSERT INTO informations(name, frequency) VALUES('Не было сэкса', 0.5);
INSERT INTO informations(name, frequency) VALUES('Седые волосы', 0.3);
INSERT INTO informations(name, frequency) VALUES('Лысый', 0.4);
INSERT INTO informations(name, frequency) VALUES('Четвертая группа крови', 0.1);
INSERT INTO informations(name, frequency) VALUES('Умеет играть на гитаре', 0.6);
INSERT INTO informations(name, frequency) VALUES('Умеет программировать', 0.6);
INSERT INTO informations(name, frequency) VALUES('Работал автомехаником', 0.4);