INSERT INTO healths(name, frequency) VALUES ('ВИЧ', 0.2);
INSERT INTO healths(name, frequency) VALUES ('СПИД', 0.1);
INSERT INTO healths(name, frequency) VALUES('Идеально здоров', 1);
INSERT INTO healths(name, frequency) VALUES('Не обследовался', 1);
INSERT INTO healths(name, frequency) VALUES('Сифилис', 0.2);
INSERT INTO healths(name, frequency) VALUES('Дерматит', 0.5);
INSERT INTO healths(name, frequency) VALUES('Нет руки', 0.1);
INSERT INTO healths(name, frequency) VALUES('Нет ноги', 0.1);
INSERT INTO healths(name, frequency) VALUES('Нет пальца', 0.2);
INSERT INTO healths(name, frequency) VALUES('СДВГ', 0.5);
INSERT INTO healths(name, frequency) VALUES('Гипертония', 0.4);
INSERT INTO healths(name, frequency) VALUES('Рак кожи', 0.1);
INSERT INTO healths(name, frequency) VALUES('Рак мозга', 0.1);
INSERT INTO healths(name, frequency) VALUES('Гемофилия ', 0.1);
INSERT INTO healths(name, frequency) VALUES('Сколиоз', 0.5);
INSERT INTO healths(name, frequency) VALUES('Кифоз', 0.7);
INSERT INTO healths(name, frequency) VALUES('Лордоз', 0.7);
INSERT INTO healths(name, frequency) VALUES('Плоскостопие', 0.7);
INSERT INTO healths(name, frequency) VALUES('Близорукость', 0.4);
INSERT INTO healths(name, frequency) VALUES('Остеохондроз', 0.3);
INSERT INTO healths(name, frequency) VALUES('Синусит', 0.5);
INSERT INTO healths(name, frequency) VALUES('Вазоматорный ринит', 0.3);
INSERT INTO healths(name, frequency) VALUES('Перелом руки', 0.6);
INSERT INTO healths(name, frequency) VALUES('ИБС', 0.1);
INSERT INTO healths(name, frequency) VALUES('ДЦП', 0.1);
INSERT INTO healths(name, frequency) VALUES('Туберкулез', 0.1);
INSERT INTO healths(name, frequency) VALUES('Простуда', 1);
INSERT INTO healths(name, frequency) VALUES('Аскаридоз', 0.1);
INSERT INTO healths(name, frequency) VALUES('Герпес', 0.6);
INSERT INTO healths(name, frequency) VALUES('Гонорея', 0.4);
INSERT INTO healths(name, frequency) VALUES('Понос', 0.4);
INSERT INTO healths(name, frequency) VALUES('Диарея', 0.6);
INSERT INTO healths(name, frequency) VALUES('Запор', 0.6);
INSERT INTO healths(name, frequency) VALUES('ПТСР', 0.2);
INSERT INTO healths(name, frequency) VALUES('Псориаз', 0.8);
INSERT INTO healths(name, frequency) VALUES('Диабет I типа', 0.3);
INSERT INTO healths(name, frequency) VALUES('Диабет II типа', 0.8);
INSERT INTO healths(name, frequency) VALUES('Алкоголизм', 0.4);
INSERT INTO healths(name, frequency) VALUES('Наркомания', 0.1);
INSERT INTO healths(name, frequency) VALUES('Папилломы', 0.8);
INSERT INTO healths(name, frequency) VALUES('Бородавки', 0.8);
INSERT INTO healths(name, frequency) VALUES('Психопатия', 0.3);
INSERT INTO healths(name, frequency) VALUES('Геморрой', 0.9);
INSERT INTO healths(name, frequency) VALUES('Варикоз', 0.9);
INSERT INTO healths(name, frequency) VALUES('Бронхит', 0.5);
INSERT INTO healths(name, frequency) VALUES('Синдром раздраженного кишечника', 0.4);
INSERT INTO healths(name, frequency) VALUES('Отит', 0.6);
INSERT INTO healths(name, frequency) VALUES('Плохой слух', 0.7);
INSERT INTO healths(name, frequency) VALUES('Глухой', 0.3);
INSERT INTO healths(name, frequency) VALUES('Немой', 0.3);
INSERT INTO healths(name, frequency) VALUES('Нет половины зубов', 0.2);
INSERT INTO healths(name, frequency) VALUES('Кариес', 0.5);
INSERT INTO healths(name, frequency) VALUES('Бесплодие', 0.3);
INSERT INTO healths(name, frequency) VALUES('Пигментные пятна', 0.8);
INSERT INTO healths(name, frequency) VALUES('Деменция', 0.1);
INSERT INTO healths(name, frequency) VALUES('Энурез', 0.4);
INSERT INTO healths(name, frequency) VALUES('Слепота на 1 глаз', 0.4);
INSERT INTO healths(name, frequency) VALUES('Слепота', 0.2);
INSERT INTO healths(name, frequency) VALUES('Невроз', 0.5);
INSERT INTO healths(name, frequency) VALUES('Фиброз легких', 0.6);
INSERT INTO healths(name, frequency) VALUES('Ишурия', 0.4);
INSERT INTO healths(name, frequency) VALUES('Пупочная грыжа', 0.7);
INSERT INTO healths(name, frequency) VALUES('Неправильный прикус', 1);
INSERT INTO healths(name, frequency) VALUES('Роговая кератома', 0.7);
INSERT INTO healths(name, frequency) VALUES('Гепатит A', 0.8);
INSERT INTO healths(name, frequency) VALUES('Гепатит B', 0.5);
