INSERT INTO inventories(name, frequency) VALUES('Гитара', 0.5);
INSERT INTO inventories(name, frequency) VALUES('Укулеле', 0.3);
INSERT INTO inventories(name, frequency) VALUES('Кожачий корм', 0.5);
INSERT INTO inventories(name, frequency) VALUES('Собачий корм', 0.6);
INSERT INTO inventories(name, frequency) VALUES('Лезвия и крем для бритья', 0.5);
INSERT INTO inventories(name, frequency) VALUES('Одежда', 0.5);
INSERT INTO inventories(name, frequency) VALUES('Пистолет и патроны', 0.3);
INSERT INTO inventories(name, frequency) VALUES('Заряженный автомат', 0.1);
INSERT INTO inventories(name, frequency) VALUES('Сигареты', 0.6);
INSERT INTO inventories(name, frequency) VALUES('Ящик пива', 0.4);
INSERT INTO inventories(name, frequency) VALUES('Игра "Монополия"', 0.3);
INSERT INTO inventories(name, frequency) VALUES('Шахматы', 0.3);
INSERT INTO inventories(name, frequency) VALUES('Бумага и карандаши', 0.2);
INSERT INTO inventories(name, frequency) VALUES('Парик', 0.1);
INSERT INTO inventories(name, frequency) VALUES('Оплодотворенные куриные яйца', 0.3);
INSERT INTO inventories(name, frequency) VALUES('Инкубатор', 0.1);
INSERT INTO inventories(name, frequency) VALUES('Мешок картошки', 0.3);
INSERT INTO inventories(name, frequency) VALUES('Мешок риса', 0.4);
INSERT INTO inventories(name, frequency) VALUES('Ремонтный набор', 0.2);
INSERT INTO inventories(name, frequency) VALUES('Новые кроссовки', 0.4);
INSERT INTO inventories(name, frequency) VALUES('Раскладушка', 0.1);
INSERT INTO inventories(name, frequency) VALUES('Антибиотики', 0.2);
INSERT INTO inventories(name, frequency) VALUES('Аптечка', 0.4);
INSERT INTO inventories(name, frequency) VALUES('Канистра бензина', 0.3);
INSERT INTO inventories(name, frequency) VALUES('Книга рецептов', 0.4);
INSERT INTO inventories(name, frequency) VALUES('Книги по физике', 0.2);
INSERT INTO inventories(name, frequency) VALUES('Книги по программированию', 0.3);
INSERT INTO inventories(name, frequency) VALUES('10 литров воды', 0.6);
INSERT INTO inventories(name, frequency) VALUES('Ноутбук', 0.8);
INSERT INTO inventories(name, frequency) VALUES('Шоппер с продуктами', 1);
INSERT INTO inventories(name, frequency) VALUES('Лопата', 0.3);
INSERT INTO inventories(name, frequency) VALUES('Топор', 0.4);
INSERT INTO inventories(name, frequency) VALUES('Ножик', 0.8);
INSERT INTO inventories(name, frequency) VALUES('Нож', 0.8);
INSERT INTO inventories(name, frequency) VALUES('Швейцарский нож', 0.9);
INSERT INTO inventories(name, frequency) VALUES('Отвертка', 0.5);