INSERT INTO characters(name, frequency) VALUES ('Интроверт', 0.3);
INSERT INTO characters(name, frequency) VALUES ('Экстраверт', 0.6);
INSERT INTO characters(name, frequency) VALUES ('Решительный', 0.5);
INSERT INTO characters(name, frequency) VALUES ('Уверенный в себе', 0.5);
INSERT INTO characters(name, frequency) VALUES ('Агрессивный', 0.6);
INSERT INTO characters(name, frequency) VALUES ('Скромный', 0.4);
INSERT INTO characters(name, frequency) VALUES ('Плаксивый', 0.3);
INSERT INTO characters(name, frequency) VALUES ('Сангвиник', 0.3);
INSERT INTO characters(name, frequency) VALUES ('Пессимист', 0.4);
INSERT INTO characters(name, frequency) VALUES ('Добрый', 0.6);
INSERT INTO characters(name, frequency) VALUES ('Ответственный', 0.4);
INSERT INTO characters(name, frequency) VALUES ('Честный ', 0.3);
INSERT INTO characters(name, frequency) VALUES ('Смелый', 0.3);
INSERT INTO characters(name, frequency) VALUES ('Ленивый', 0.3);
INSERT INTO characters(name, frequency) VALUES ('Алчный', 0.5);
INSERT INTO characters(name, frequency) VALUES ('Грубый', 0.5);
INSERT INTO characters(name, frequency) VALUES ('Лицемерный', 0.2);
INSERT INTO characters(name, frequency) VALUES ('Коварный', 0.2);
INSERT INTO characters(name, frequency) VALUES ('Стрессоустойчивый', 0.3);
INSERT INTO characters(name, frequency) VALUES ('Циничный', 0.3);
INSERT INTO characters(name, frequency) VALUES ('Пошлый', 0.3);
INSERT INTO characters(name, frequency) VALUES ('Эгоистичный', 0.6);
INSERT INTO characters(name, frequency) VALUES ('Харизматичный', 0.7);
INSERT INTO characters(name, frequency) VALUES ('Артистичный', 0.3);
INSERT INTO characters(name, frequency) VALUES ('Инфантильный', 0.3);
