INSERT INTO hobbies(name, frequency) VALUES('Шахматы', 0.7);
INSERT INTO hobbies(name, frequency) VALUES('Футбол', 0.7);
INSERT INTO hobbies(name, frequency) VALUES('Настольные игры', 0.4);
INSERT INTO hobbies(name, frequency) VALUES('Спорт', 0.3);
INSERT INTO hobbies(name, frequency) VALUES('Тренажерный зал', 0.6);
INSERT INTO hobbies(name, frequency) VALUES('Садоводства', 0.2);
INSERT INTO hobbies(name, frequency) VALUES('Кулинария', 0.4);
INSERT INTO hobbies(name, frequency) VALUES('БДСМ', 0.2);
INSERT INTO hobbies(name, frequency) VALUES('Косплей', 0.2);
INSERT INTO hobbies(name, frequency) VALUES('Баскетбол', 0.4);
INSERT INTO hobbies(name, frequency) VALUES('Анатомия', 0.1);
INSERT INTO hobbies(name, frequency) VALUES('Астрология', 0.5);
INSERT INTO hobbies(name, frequency) VALUES('Физика ', 0.3);
INSERT INTO hobbies(name, frequency) VALUES('Стриптиз', 0.2);
INSERT INTO hobbies(name, frequency) VALUES('Танцы', 0.4);
INSERT INTO hobbies(name, frequency) VALUES('Вокал', 0.3);
INSERT INTO hobbies(name, frequency) VALUES('Игра на гитаре', 0.5);
INSERT INTO hobbies(name, frequency) VALUES('Шитье', 0.2);
INSERT INTO hobbies(name, frequency) VALUES('Электроника', 0.2);