INSERT INTO healths(name, frequency) VALUES ('ВИЧ', 0.2);
INSERT INTO healths(name, frequency) VALUES('Идеально здоров', 0.3);
INSERT INTO healths(name, frequency) VALUES('Не обследовался', 0.9);
INSERT INTO healths(name, frequency) VALUES('Сифилис', 0.2);
INSERT INTO healths(name, frequency) VALUES('Дерматит', 0.5);
INSERT INTO healths(name, frequency) VALUES('Нет руки', 0.1);
INSERT INTO healths(name, frequency) VALUES('Нет ноги', 0.1);
INSERT INTO healths(name, frequency) VALUES('Нет пальца', 0.2);
INSERT INTO healths(name, frequency) VALUES('СДВГ', 0.5);
INSERT INTO healths(name, frequency) VALUES('Гипертония', 0.4);
INSERT INTO healths(name, frequency) VALUES('Рак кожи', 0.1);
INSERT INTO healths(name, frequency) VALUES('Рак мозга', 0.1);
INSERT INTO healths(name, frequency) VALUES('Гемофилия ', 0.1);
INSERT INTO healths(name, frequency) VALUES('Сколиоз', 0.5);
INSERT INTO healths(name, frequency) VALUES('Кифоз', 0.7);
INSERT INTO healths(name, frequency) VALUES('Лордоз', 0.7);
INSERT INTO healths(name, frequency) VALUES('Плоскостопие', 0.7);
INSERT INTO healths(name, frequency) VALUES('Близорукость', 0.4);
INSERT INTO healths(name, frequency) VALUES('Остеохондроз', 0.3);